version: '3.3'

networks:
  mfc:

services:
  wallet:
    image: kamehb/mfc-wallet-daemon:3.0.0.2
    networks:
      - mfc
    command:
      - -txindex
      - -reindex
      - -rpcuser=${RPC_USER}
      - -rpcpassword=${RPC_PASS}
      - -rpcallowip=0.0.0.0/0
    volumes:
      - ./data/wallet:/root/.MFC
  server:
    image: kamehb/mfc-electrumx-server:1.13.0
    networks:
      - mfc
    environment:
      - COIN=MFCoin
      - DB_DIRECTORY=/var/db/electrumx
      - DAEMON_URL=http://${RPC_USER}:${RPC_PASS}@wallet:22825
      - ALLOW_ROOT=1
      - SERVICES=tcp://:23000,rpc://:8000
    ports:
      - 23000:23000
    depends_on:
      - wallet
    volumes:
      - ./data/server:/var/db/electrumx
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
