version: '3.3'

networks:
  mfc:

services:
  daemon:
    build:
      context: daemon
      args:
          USE_OLD_BERKLEYDB: 'false'
    networks:
      - mfc
    command:
      - -txindex
      - -reindex
      - -rpcuser=${RPC_USER}
      - -rpcpassword=${RPC_PASS}
      - -rpcallowip=0.0.0.0/0
    volumes:
      - ./data/wallet:/root/.MFC
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    restart: always
  server:
    build: server
    networks:
      - mfc
    environment:
      - COIN=MFCoin
      - DB_DIRECTORY=/var/db/electrumx
      - DAEMON_URL=http://${RPC_USER}:${RPC_PASS}@daemon:22825
      - ALLOW_ROOT=1
      - SERVICES=ssl://:23000,ws://:23001
      - SSL_CERTFILE=/data/electrumx.crt
      - SSL_KEYFILE=/data/electrumx.key
    ports:
      - 23000:23000
      - 23001:23001
    depends_on:
      - daemon
    volumes:
      - ./data/server:/var/db/electrumx
      - ${SSL_CERTFILE}:/data/electrumx.crt:ro
      - ${SSL_KEYFILE}:/data/electrumx.key:ro
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    restart: always
